groups:
- name: slack-notifications
  rules:
  - alert: InstanceDown
    # Condition for alerting
    expr: up == 0
    for: 5s
    # Labels - additional labels to be attached to the alert
    labels:
        severity: 'critical'
