{
 "title": "Nginx Dashboard",
 "description": "Shows stats built from the Prometheus Nginx mtail log exporter rebuy-de/nginx-exporter or ndiazg/nginx-prometheus-exporter.",
 "tags": [
  "nginx",
  "http"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(nginx_up, namespace)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(nginx_up{namespace=~\"$namespace\"}, app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Prometheus Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scrape durations in seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "scrape_duration_seconds{}", "legendFormat": "seconds" }
     ]
    }
   ]
  },
  { "title": "Overall Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Active & Waiting Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_http_connections{state=\"active\"}",
     "legendFormat": "active connections"
    },
    {
     "expr": "nginx_http_connections{state=\"waiting\"}",
     "legendFormat": "waiting connections"
    }
   ]
  },
  {
   "title": " HTTP Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_request_time_sum{host!=\"127.0.0.1\"}[1m])) / sum(rate(nginx_http_request_time_count{host!=\"127.0.0.1\"}[1m]))",
     "legendFormat": "milliseconds"
    }
   ]
  },
  {
   "title": " HTTP Response sizes in bytes",
   "type": "graph",
   "description": "Response sizes in bytes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_http_request_bytes_sent{}[5m])) by (host)",
     "legendFormat": "{{ host }}"
    },
    {}
   ]
  },
  {
   "title": "HTTP Status codes per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests{}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HTTP Requests By Host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_http_requests{}[5m])) by (host,status)",
     "legendFormat": "{{status}} {{host}}"
    }
   ]
  },
  { "title": "Upstream Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Upstream Server Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_http_upstream_requests{status!=\"-\"}[5m])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Upstream Server Bytes Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_http_upstream_bytes_received{}[5m])) by (addr)",
     "legendFormat": "{{ addr }}"
    }
   ]
  }
 ]
}